      SUBROUTINE CPUSEC (T)
C     *
C     ROUTINE FOR TIMING (CPU TIME IN SECONDS).
C     *
      DOUBLE PRECISION T
CUNIX VERSION FOR UNIX MACHINES WHICH PROVIDE A LIBRARY FUNCTION ETIME.
      REAL ETIME,TARRAY,TOTAL
      DIMENSION TARRAY(2)
      TTOTAL = ETIME(TARRAY)
      T      = TARRAY(1)
CIBM  VERSION FOR IBM RS/6000 WHICH PROVIDES A LIBRARY FUNCTION MCLOCK.
c      INTEGER I
c        I      = MCLOCK()
c        T      = I/100.0D0
CRAY  VERSION FOR CRAY WHICH PROVIDES A LIBRARY ROUTINE SECOND.
c          CALL SECOND(T)
CNEC  VERSION FOR NEC WHICH PROVIDES A LIBRARY ROUTINE CLOCK.
C     CALL CLOCK(T)
CSNI  VERSION FOR SNI-FUJITSU WHICH PROVIDES A LIBRARY ROUTINE CLOCK.
C     CALL CLOCK(T,0,2)
CONV  VERSION FOR CONVEX WHICH PROVIDES A VECLIB FUNCTION CPUTIME.
C     REAL CPUTIME
C     T      = CPUTIME(0.0)
      RETURN
      END
