subroutine twoe_pppp(mindex,zabcd,za_plus_zb,zc_plus_zd,ishellpa,ishellpb,ishellpc,ishellpd,pvector,qvector,wvector,ppppints)
use gaussian_basis
implicit double precision (a-h,o-z)
interface
subroutine twoe_ppps(mindex,zabcd,za_plus_zb,zc_plus_zd,ishellpa,ishellpb,ishellpc,pvector,qvector,wvector,pppsints)
integer,intent(in)::mindex
double precision,intent(in)::zabcd,za_plus_zb,zc_plus_zd
integer,intent(in)::ishellpa,ishellpb,ishellpc
double precision,dimension(:),intent(in)::pvector,qvector,wvector
double precision,intent(inout),dimension(3,3,3)::pppsints
end subroutine twoe_ppps

subroutine twoe_psps(mindex,zabcd,za_plus_zb,zc_plus_zd,ishellpa,ishellpb,pvector,qvector,wvector,pspsints)
integer,intent(in)::mindex
double precision,intent(in)::zabcd,za_plus_zb,zc_plus_zd
integer,intent(in)::ishellpa,ishellpb
double precision,dimension(:),intent(in)::pvector,qvector,wvector
double precision,dimension(:,:),intent(inout)::pspsints
end subroutine twoe_psps

end interface



integer,intent(in)::mindex
double precision,intent(in)::zabcd,za_plus_zb,zc_plus_zd
integer,intent(in)::ishellpa,ishellpb,ishellpc,ishellpd
double precision,dimension(:),intent(in)::pvector,qvector,wvector
double precision,dimension(:,:,:,:),intent(inout)::ppppints
double precision,dimension(3,3,3)::pppsints
double precision,dimension(3)::qlldl,wllql
double precision,dimension(3,3)::pspsints

pi=dacos(-1.0d0)



do i=1,3
qlldl(i)=qvector(i)-shell_coor(i,ishellpd)
wllql(i)=wvector(i)-qvector(i)
end do


call twoe_ppps(mindex,zabcd,za_plus_zb,zc_plus_zd,ishellpa,ishellpb,ishellpc,pvector,qvector,wvector,pppsints)


do l=1,3
do k=1,3
do j=1,3
do i=1,3
ppppints(i,j,k,l)=qlldl(l)*pppsints(i,j,k)
end do
end do
end do
end do
! do delta(kl) part using ppss ints generated by ppps 

factor=1.0d0/(2.0d0*zc_plus_zd)
factor2=factor*za_plus_zb/zabcd
do k=1,3
do j=1,3
do i=1,3
ppppints(i,j,k,k)=ppppints(i,j,k,k)+factor*ppssints_global(i,j) - factor2 *ppssintsmp1_global(i,j) 
end do 
end do 
end do

call twoe_ppps(mindex+1,zabcd,za_plus_zb,zc_plus_zd,ishellpa,ishellpb,ishellpc,pvector,qvector,wvector,pppsints)

do l=1,3
do k=1,3
do j=1,3
do i=1,3
ppppints(i,j,k,l)=ppppints(i,j,k,l)+wllql(l)*pppsints(i,j,k)
end do
end do
end do
end do


call twoe_psps(mindex+1,zabcd,za_plus_zb,zc_plus_zd,ishellpb,ishellpc,pvector,qvector,wvector,pspsints)

factor=1.0d0/(2.0d0*zabcd)
do k=1,3
do j=1,3
do i=1,3
ppppints(i,j,k,i)=ppppints(i,j,k,i)+factor*pspsints(j,k)
end do
end do
end do


call twoe_psps(mindex+1,zabcd,za_plus_zb,zc_plus_zd,ishellpa,ishellpc,pvector,qvector,wvector,pspsints)

do k=1,3
do j=1,3
do i=1,3
ppppints(i,j,k,j)=ppppints(i,j,k,j)+factor*pspsints(i,k)
end do
end do
end do





return
end


